"""
LLM module for the RAG pipeline.
Handles the initialization and execution of the Large Language Model (set to Qwen in config.py).
"""

from __future__ import annotations

import os

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from src.config import RAGConfig


# Enable silent fallback to CPU for operations not natively supported by the Metal Performance Shaders (MPS) backend.
# This environment variable must be initialized prior to any tensor instantiation.
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")


class LLMClient:
    """
    Interface for the autoregressive Language Model (natively Qwen2.5-1.5B-Instruct).
    
    Configured specifically for Apple Silicon architecture, enforcing FP16 (to reduce RAM needed).
    Then it enforces deterministic (greedy) generation to guarantee reproducibility and aligning with 
    the conservative generation needed for the risky context in which we act (medical)
    """

    def __init__(self, config: RAGConfig) -> None:
        self.config = config

        self._tokenizer = AutoTokenizer.from_pretrained(config.model_id)

        # Instantiate the model in evaluation mode to disable stochastic training layers (e.g., Dropout).
        # device_map="mps" eagerly maps all model layers to the Apple Silicon GPU.
        self._model = AutoModelForCausalLM.from_pretrained(
            config.model_id,
            torch_dtype=torch.float16,
            device_map="mps",
        )
        self._model.eval()  # turns off training-mode behaviours (like drop-out)

        # Cache the device reference to optimize tensor device transfer during inference.
        self._device: torch.device = next(self._model.parameters()).device

    def generate(self, messages: list[dict[str, str]]) -> str:
        """
        Processes a structured chat history through the deterministic model.

        Args:
            messages: A sequence of message dictionaries conforming to the OpenAI chat structure
                      (e.g., [{"role": "system", "content": "..."}, ...]).

        Returns:
            The raw text output generated by the model, stripped of the initial prompt tokens.
        """
        # Apply model-specific control tokens (chat template) to format the context window.
        prompt: str = self._tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,  # so the model knows it should speak next
        )

        inputs = self._tokenizer(prompt, return_tensors="pt").to(self._device) # send them to MPS
        n_prompt_tokens: int = inputs["input_ids"].shape[1]

        # Execute forward pass without gradient tracking (since we are not training)
        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                max_new_tokens=self.config.max_new_tokens,
                do_sample=False, # Strictly enforce greedy decoding for deterministic outputs.
                pad_token_id=self._tokenizer.eos_token_id,
            )

        # Isolate the newly generated token sequence from the contextual prompt.
        new_token_ids = output_ids[0, n_prompt_tokens:]
        return self._tokenizer.decode(new_token_ids, skip_special_tokens=True).strip()
